# Generated by Django 2.0.9 on 2018-11-30 15:02

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=s3upload.fields.S3UploadField(dest='default'),
        ),
    ]
