language: python
python: '3.6'
services:
  - postgresql
env:
  - DJANGO_SETTINGS_MODULE=config.settings.test
install:
  - pip install -r requirements/test.txt
before_script:
  - sudo apt-get install -y pandoc pandoc-citeproc
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - coverage run manage.py test
after_success:
  - coveralls
notifications:
  email:
    - mb@scholarium.at
